version: '3.9'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}converterapi
    build:
      context: .
      dockerfile: src/ConverterApi/Dockerfile
    environment:
       - AppConverter=libreoffice